#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-only
set -eu

reference_dir=${1:-target/design-qa/reference}
capture_dir=${2:-target/design-qa/capture}
output_dir=${3:-target/design-qa/comparison}

command -v magick >/dev/null 2>&1 || {
    echo 'compare-macos-ui: ImageMagick (magick) is required' >&2
    exit 69
}
[ -d "$reference_dir" ] || {
    echo "compare-macos-ui: reference directory not found: $reference_dir" >&2
    exit 66
}
[ -d "$capture_dir" ] || {
    echo "compare-macos-ui: capture directory not found: $capture_dir" >&2
    exit 66
}

mkdir -p "$output_dir"
metrics="$output_dir/metrics.tsv"
: > "$metrics"
printf 'scene\tssim\n' >> "$metrics"

contact_inputs=
for reference in "$reference_dir"/R*.png; do
    [ -f "$reference" ] || continue
    name=$(basename "$reference")
    scene=${name%.png}
    capture="$capture_dir/$name"
    [ -f "$capture" ] || {
        echo "compare-macos-ui: missing capture: $capture" >&2
        exit 66
    }

    normalized="$output_dir/$scene-normalized.png"
    side_by_side="$output_dir/$scene-side-by-side.png"
    overlay="$output_dir/$scene-overlay.png"
    heatmap="$output_dir/$scene-heatmap.png"
    dimensions=$(magick identify -format '%wx%h' "$reference")
    # Preserve aspect ratio. Native chrome and the taller Logs viewport are
    # intentional differences and must never be disguised by stretching.
    magick "$capture" -resize "$dimensions" -background white -gravity center -extent "$dimensions" "$normalized"
    magick "$reference" "$normalized" +append "$side_by_side"
    magick "$reference" "$normalized" -alpha on -compose blend -define compose:args=50,50 -composite "$overlay"
    magick compare -metric SSIM "$reference" "$normalized" "$heatmap" 2> "$output_dir/$scene-ssim.txt" || true
    ssim=$(tr -d '[:space:]' < "$output_dir/$scene-ssim.txt")
    printf '%s\t%s\n' "$scene" "$ssim" >> "$metrics"
    contact_inputs="$contact_inputs $side_by_side"
done

[ -n "$contact_inputs" ] || {
    echo 'compare-macos-ui: no R*.png references found' >&2
    exit 66
}

# Paths are generated by this script from fixed scene filenames.
# shellcheck disable=SC2086
magick montage $contact_inputs -tile 1x -geometry +0+10 "$output_dir/contact-sheet.png"
echo "compare-macos-ui: wrote $output_dir"
