#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only

from __future__ import annotations

import contextlib
import hashlib
import importlib.util
import io
import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch


SCRIPT = Path(__file__).with_name("sync-ecosystem-versions.py")
PRODUCT_VERSION = "2026.36.2"


def write(path: Path, contents: str | bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(contents, bytes):
        path.write_bytes(contents)
    else:
        path.write_text(contents, encoding="utf-8")


def load_script():
    spec = importlib.util.spec_from_file_location("g3_ecosystem_versions", SCRIPT)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load ecosystem version script")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def candidate_record(profile_id: str, profile_revision: str) -> str:
    return json.dumps(
        {
            "schema_version": 1,
            "status": "candidate",
            "product_version": PRODUCT_VERSION,
            "profile": {
                "id": profile_id,
                "revision": profile_revision,
                "sha256": None,
            },
            "tested_hub_versions": [],
            "tested_hub_source_fingerprints": [],
            "required_capabilities": [],
            "optional_capabilities": [],
            "test_receipt_paths": [],
        },
        indent=2,
    ) + "\n"


def make_active_workspace(root: Path, module) -> tuple[dict[str, str], dict[str, str]]:
    write(
        root / "hub/Cargo.toml",
        f'[package]\nname = "teslatlas-hub"\nversion = "{PRODUCT_VERSION}"\n',
    )
    write(
        root / "hub/Cargo.lock",
        "version = 4\n\n[[package]]\nname = \"teslatlas-hub\"\n"
        f'version = "{PRODUCT_VERSION}"\n',
    )
    write(
        root / "teslatlas-protocol/pyproject.toml",
        '[project]\nname = "teslatlas-protocol-conformance"\n'
        f'version = "{PRODUCT_VERSION}"\n',
    )
    write(
        root / "teslatlas-protocol/uv.lock",
        "version = 1\nrevision = 3\n\n[[package]]\n"
        'name = "teslatlas-protocol-conformance"\n'
        f'version = "{PRODUCT_VERSION}"\n',
    )
    write(root / "teslatlas-protocol/VERSION", f"{PRODUCT_VERSION}\n")
    write(
        root / "teslatlas-sdk-typescript/package.json",
        json.dumps({"name": "@teslatlas/sdk", "version": PRODUCT_VERSION}, indent=2) + "\n",
    )
    write(
        root / "teslatlas-sdk-typescript/package-lock.json",
        json.dumps(
            {
                "name": "@teslatlas/sdk",
                "version": PRODUCT_VERSION,
                "lockfileVersion": 3,
                "packages": {"": {"name": "@teslatlas/sdk", "version": PRODUCT_VERSION}},
            },
            indent=2,
        ) + "\n",
    )
    write(root / "teslatlas-sdk-swift/VERSION", f"{PRODUCT_VERSION}\n")
    write(
        root / "teslatlas-sdk-swift/Sources/TeslatlasHubSDK/ProductVersion.swift",
        "// @generated by hub/scripts/sync-ecosystem-versions.py\n"
        f'public let teslatlasProductVersion = "{PRODUCT_VERSION}"\n',
    )
    write(
        root / "teslatlas-edge/Cargo.toml",
        f'[package]\nname = "teslatlas-edge"\nversion = "{PRODUCT_VERSION}"\n',
    )
    write(
        root / "teslatlas-edge/Cargo.lock",
        "version = 4\n\n[[package]]\nname = \"teslatlas-edge\"\n"
        f'version = "{PRODUCT_VERSION}"\n',
    )

    hub_record = candidate_record("hub-http-v1", "1.0.0")
    edge_record = candidate_record("edge-delivery-v2", "2.0.0")
    for relative in (
        "teslatlas-protocol/compatibility/hub.json",
        "teslatlas-sdk-typescript/protocol/source/compatibility/hub.json",
        "teslatlas-sdk-typescript/compatibility/hub.json",
        "teslatlas-sdk-swift/compatibility/hub.json",
    ):
        write(root / relative, hub_record)
    write(root / "teslatlas-edge/compatibility/hub.json", edge_record)

    receipt_hashes: dict[str, str] = {}
    for index, relative in enumerate(module.G3_RECEIPTS):
        contents = json.dumps({"result": "ACCEPTED", "fixture": index}, sort_keys=True) + "\n"
        write(root / relative, contents)
        receipt_hashes[relative] = hashlib.sha256(contents.encode()).hexdigest()

    profile_hashes: dict[str, str] = {}
    for index, relative in enumerate(module.G3_PROFILE_BINDINGS):
        contents = f"g3-profile-fixture-{index}\n".encode()
        write(root / relative, contents)
        profile_hashes[relative] = hashlib.sha256(contents).hexdigest()
    return receipt_hashes, profile_hashes


class G3ScopedAdmissionTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.module = load_script()

    def fixture(self, directory: str):
        workspace = Path(directory).resolve()
        receipt_hashes, profile_hashes = make_active_workspace(workspace, self.module)
        return workspace, receipt_hashes, profile_hashes

    def run_with_identities(
        self,
        workspace: Path,
        receipt_hashes: dict[str, str],
        profile_hashes: dict[str, str],
        mode: str,
    ) -> tuple[int, str, str]:
        stdout = io.StringIO()
        stderr = io.StringIO()
        with (
            patch.object(self.module, "G3_RECEIPTS", receipt_hashes),
            patch.object(self.module, "G3_PROFILE_BINDINGS", profile_hashes),
            contextlib.redirect_stdout(stdout),
            contextlib.redirect_stderr(stderr),
        ):
            result = self.module.main(["--workspace", str(workspace), mode])
        return result, stdout.getvalue(), stderr.getvalue()

    def test_admission_succeeds_with_only_active_g3_products(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            workspace, receipt_hashes, profile_hashes = self.fixture(directory)

            result, stdout, stderr = self.run_with_identities(
                workspace, receipt_hashes, profile_hashes, "--admit-g3"
            )

            self.assertEqual(result, 0, stderr)
            self.assertEqual(stderr, "")
            self.assertIn("was admitted", stdout)

    def test_admission_is_idempotent(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            workspace, receipt_hashes, profile_hashes = self.fixture(directory)
            record_paths = [workspace / relative for relative in self.module._g3_specifications()]

            first = self.run_with_identities(
                workspace, receipt_hashes, profile_hashes, "--admit-g3"
            )
            accepted_bytes = {path: path.read_bytes() for path in record_paths}
            second = self.run_with_identities(
                workspace, receipt_hashes, profile_hashes, "--admit-g3"
            )

            self.assertEqual(first[0], 0, first[2])
            self.assertEqual(second[0], 0, second[2])
            self.assertEqual({path: path.read_bytes() for path in record_paths}, accepted_bytes)

    def test_wrong_receipt_identity_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            workspace, receipt_hashes, profile_hashes = self.fixture(directory)
            relative = next(iter(receipt_hashes))
            write(workspace / relative, '{"result":"ACCEPTED","changed":true}\n')

            result, _, stderr = self.run_with_identities(
                workspace, receipt_hashes, profile_hashes, "--admit-g3"
            )

            self.assertEqual(result, 1)
            self.assertIn("G3 receipt identity mismatch", stderr)

    def test_wrong_profile_digest_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            workspace, receipt_hashes, profile_hashes = self.fixture(directory)
            relative = next(iter(profile_hashes))
            write(workspace / relative, b"changed-profile\n")

            result, _, stderr = self.run_with_identities(
                workspace, receipt_hashes, profile_hashes, "--admit-g3"
            )

            self.assertEqual(result, 1)
            self.assertIn("G3 profile identity mismatch", stderr)

    def test_divergent_accepted_record_is_refused(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            workspace, receipt_hashes, profile_hashes = self.fixture(directory)
            admitted = self.run_with_identities(
                workspace, receipt_hashes, profile_hashes, "--admit-g3"
            )
            self.assertEqual(admitted[0], 0, admitted[2])
            relative = "teslatlas-sdk-typescript/compatibility/hub.json"
            record_path = workspace / relative
            record = json.loads(record_path.read_text(encoding="utf-8"))
            record["test_receipt_paths"] = record["test_receipt_paths"][:1]
            write(record_path, json.dumps(record, indent=2) + "\n")

            result, _, stderr = self.run_with_identities(
                workspace, receipt_hashes, profile_hashes, "--admit-g3"
            )

            self.assertEqual(result, 1)
            self.assertIn("refusing to rewrite a different accepted G3 record", stderr)

    def test_scoped_post_check_reads_back_exact_records(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            workspace, receipt_hashes, profile_hashes = self.fixture(directory)
            admitted = self.run_with_identities(
                workspace, receipt_hashes, profile_hashes, "--admit-g3"
            )
            self.assertEqual(admitted[0], 0, admitted[2])

            result, stdout, stderr = self.run_with_identities(
                workspace, receipt_hashes, profile_hashes, "--check-g3"
            )

            self.assertEqual(result, 0, stderr)
            self.assertEqual(stderr, "")
            self.assertIn("is aligned", stdout)
            self.assertEqual(
                (workspace / "teslatlas-protocol/compatibility/hub.json").read_bytes(),
                (
                    workspace
                    / "teslatlas-sdk-typescript/protocol/source/compatibility/hub.json"
                ).read_bytes(),
            )


if __name__ == "__main__":
    unittest.main()
