// SPDX-License-Identifier: AGPL-3.0-only
import {createHash} from 'node:crypto';
import {open,realpath,stat} from 'node:fs/promises';
import net from 'node:net';
import path from 'node:path';

const FRAME_BYTES=1048576;
const OPERATION_MS=Object.freeze({verify:30000,stop:60000,start:60000,pair:160000,revoke:160000});
const sha=raw=>createHash('sha256').update(raw).digest('hex');
const exact=(value,keys,label)=>{if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).sort().join('\0')!==[...keys].sort().join('\0'))throw Error(`${label} fields invalid`);return value};
const strictJson=raw=>{
 if(!Buffer.isBuffer(raw)&&!(raw instanceof Uint8Array))throw Error('JSON input must be bytes');
 let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(raw)}catch{throw Error('JSON input is not UTF-8')}
 let index=0;
 const fail=()=>{throw Error('invalid JSON')};
 const whitespace=()=>{while(index<text.length&&(text[index]===' '||text[index]==='\t'||text[index]==='\r'||text[index]==='\n'))index++};
 const string=()=>{
  if(text[index]!=='"')return fail();const start=index++;let closed=false;
  while(index<text.length){const char=text[index++];if(char==='\\'){if(index>=text.length)return fail();index++;continue}if(char==='"'){closed=true;break}if(char<' ')return fail()}
  if(!closed)return fail();try{return JSON.parse(text.slice(start,index))}catch{return fail()}
 };
 const value=()=>{
  whitespace();const char=text[index];
  if(char==='"')return string();
  if(char==='{'){index++;const object={};whitespace();if(text[index]==='}'){index++;return object}while(true){whitespace();const key=string();if(Object.hasOwn(object,key))throw Error('duplicate JSON key');whitespace();if(text[index++]!==':')return fail();Object.defineProperty(object,key,{value:value(),enumerable:true,writable:true,configurable:true});whitespace();if(text[index]===','){index++;continue}if(text[index++]!=='}')return fail();return object}}
  if(char==='['){index++;const array=[];whitespace();if(text[index]===']'){index++;return array}while(true){array.push(value());whitespace();if(text[index]===','){index++;continue}if(text[index++]!==']')return fail();return array}}
  for(const [literal,result] of [['true',true],['false',false],['null',null]])if(text.startsWith(literal,index)){index+=literal.length;return result}
  const match=text.slice(index).match(/^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?/);if(match){index+=match[0].length;const number=Number(match[0]);if(!Number.isFinite(number))return fail();return number}
  return fail();
 };
 const result=value();whitespace();if(index!==text.length)return fail();return result;
};
const record=(value,label)=>{if(!value||typeof value!=='object'||Array.isArray(value))throw Error(`${label} must be an object`);return value};
const textValue=(value,label,{min=1,max=4096,pattern}={})=>{if(typeof value!=='string'||value.length<min||value.length>max||(pattern&&!pattern.test(value)))throw Error(`${label} invalid`);return value};
const integerValue=(value,label,{min=0,max=Number.MAX_SAFE_INTEGER}={})=>{if(!Number.isSafeInteger(value)||value<min||value>max)throw Error(`${label} invalid`);return value};
const digestValue=(value,label)=>textValue(value,label,{min:64,max:64,pattern:/^[0-9a-f]{64}$/});
const pathValue=(value,label,max=2048)=>{textValue(value,label,{max,pattern:/^\/[^\0\r\n]*$/});if(path.resolve(value)!==value)throw Error(`${label} is not canonical`);return value};
const tokenValue=(value,label,max=128)=>textValue(value,label,{max,pattern:new RegExp(`^[A-Za-z0-9][A-Za-z0-9._-]{0,${max-1}}$`)});
const proofTokenValue=(value,label)=>textValue(value,label,{max:256,pattern:/^[A-Za-z0-9][A-Za-z0-9._:-]{0,255}$/});
const uuidValue=(value,label)=>textValue(value,label,{max:36,pattern:/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i});
const uniqueStrings=(value,label)=>{if(!Array.isArray(value)||new Set(value).size!==value.length||!value.every(item=>typeof item==='string'))throw Error(`${label} invalid`);return value};
const bindingValue=(value,label)=>{exact(value,['path','sha256'],label);pathValue(value.path,`${label}.path`);digestValue(value.sha256,`${label}.sha256`);return value};
const stagedValue=(value,label)=>{exact(value,['id','root','local'],label);tokenValue(value.id,`${label}.id`);bindingValue(value.root,`${label}.root`);bindingValue(value.local,`${label}.local`);return value};
const validateSessionInput=(session)=>{
 exact(session,['schema_version','kind','run_id','cell_id','adapter_id','client_id','session_id','instance_nonce','header','case_contract','host_session','broker','inputs','actors','outputs','bounds'],'session input');
 if(session.schema_version!==1||session.kind!=='matrix-adapter-session')throw Error('session input identity invalid');
 tokenValue(session.run_id,'session.run_id');
 if(!/^(protocol_actual_hub|typescript_node|typescript_browser|swift|home_assistant|edge_v2)__(macos_arm64|debian13_amd64|debian13_arm64)$/.test(session.cell_id))throw Error('session.cell_id invalid');
 for(const key of ['adapter_id','client_id'])if(!['protocol_actual_hub','typescript_node','typescript_browser','swift','home_assistant','edge_v2'].includes(session[key]))throw Error(`session.${key} invalid`);
 uuidValue(session.session_id,'session.session_id');digestValue(session.instance_nonce,'session.instance_nonce');
 stagedValue(session.header,'session.header');stagedValue(session.case_contract,'session.case_contract');
 const host=record(session.host_session,'session.host_session');exact(host,['schema_version','kind','broker_socket','session_id','registration_sha256'],'session.host_session');
 if(host.schema_version!==1||host.kind!=='installed-host')throw Error('session.host_session identity invalid');pathValue(host.broker_socket,'session.host_session.broker_socket');uuidValue(host.session_id,'session.host_session.session_id');digestValue(host.registration_sha256,'session.host_session.registration_sha256');
 const broker=record(session.broker,'session.broker');exact(broker,['kind','socket_path'],'session.broker');
 if(broker.kind==='unix'){pathValue(broker.socket_path,'session.broker.socket_path')}else if(broker.kind==='stdio'){if(broker.socket_path!==null)throw Error('session.broker.socket_path invalid')}else throw Error('session.broker.kind invalid');
 const inputs=record(session.inputs,'session.inputs');exact(inputs,['profile_manifest','profile_members','scenario','certificate','certificate_der_sha256','product_inputs'],'session.inputs');
 stagedValue(inputs.profile_manifest,'session.inputs.profile_manifest');if(!Array.isArray(inputs.profile_members)||inputs.profile_members.length!==18)throw Error('session.inputs.profile_members invalid');inputs.profile_members.forEach((item,index)=>stagedValue(item,`session.inputs.profile_members[${index}]`));stagedValue(inputs.scenario,'session.inputs.scenario');stagedValue(inputs.certificate,'session.inputs.certificate');digestValue(inputs.certificate_der_sha256,'session.inputs.certificate_der_sha256');
 if(!Array.isArray(inputs.product_inputs)||inputs.product_inputs.length>4)throw Error('session.inputs.product_inputs invalid');inputs.product_inputs.forEach((item,index)=>{const product=record(item,`session.inputs.product_inputs[${index}]`);exact(product,['artifact_role','staged','installed_manifest','local_root'],`session.inputs.product_inputs[${index}]`);textValue(product.artifact_role,`session.inputs.product_inputs[${index}].artifact_role`);stagedValue(product.staged,`session.inputs.product_inputs[${index}].staged`);if(product.installed_manifest!==null)stagedValue(product.installed_manifest,`session.inputs.product_inputs[${index}].installed_manifest`);if(product.local_root!==null)pathValue(product.local_root,`session.inputs.product_inputs[${index}].local_root`)});
 if(!Array.isArray(session.actors)||session.actors.length<1||session.actors.length>8)throw Error('session.actors invalid');session.actors.forEach((item,index)=>{const actor=record(item,`session.actors[${index}]`);exact(actor,['id','kind','execution','runtime_ref','artifact_roles','source_roles','entrypoint_ref','input_manifest','phase_contract'],`session.actors[${index}]`);tokenValue(actor.id,`session.actors[${index}].id`);if(!['installed_controller','installed_ha_flow','installed_ha_client','current_swift_transport','edge_normal','edge_fault','protocol_http','packed_sdk_node','packed_sdk_browser'].includes(actor.kind))throw Error(`session.actors[${index}].kind invalid`);if(!['coordinator','local_worker','docker_worker','browser_worker'].includes(actor.execution))throw Error(`session.actors[${index}].execution invalid`);tokenValue(actor.runtime_ref,`session.actors[${index}].runtime_ref`);uniqueStrings(actor.artifact_roles,`session.actors[${index}].artifact_roles`);uniqueStrings(actor.source_roles,`session.actors[${index}].source_roles`);tokenValue(actor.entrypoint_ref,`session.actors[${index}].entrypoint_ref`);stagedValue(actor.input_manifest,`session.actors[${index}].input_manifest`);if(actor.phase_contract!==null)stagedValue(actor.phase_contract,`session.actors[${index}].phase_contract`)});
 const outputs=record(session.outputs,'session.outputs');exact(outputs,['normalized','actor_evidence','coordination_dir','framework_log'],'session.outputs');for(const key of Object.keys(outputs))pathValue(outputs[key],`session.outputs.${key}`);
 const bounds=record(session.bounds,'session.bounds');exact(bounds,['cell_timeout_ms','cleanup_timeout_ms','frame_bytes','evidence_bytes','framework_log_bytes'],'session.bounds');integerValue(bounds.cell_timeout_ms,'session.bounds.cell_timeout_ms',{min:1,max:3600000});if(bounds.cleanup_timeout_ms!==45000||bounds.frame_bytes!==1048576||bounds.evidence_bytes!==8388608||bounds.framework_log_bytes!==8388608)throw Error('session.bounds constants invalid');
 return session;
};
const processValue=(value,label)=>{exact(value,['pid','uid','parent_pid','boot_id','start_identity','executable_path','executable_sha256','argv_sha256'],label);integerValue(value.pid,`${label}.pid`,{min:1,max:2147483647});integerValue(value.uid,`${label}.uid`);integerValue(value.parent_pid,`${label}.parent_pid`);textValue(value.boot_id,`${label}.boot_id`);textValue(value.start_identity,`${label}.start_identity`);pathValue(value.executable_path,`${label}.executable_path`,1024);digestValue(value.executable_sha256,`${label}.executable_sha256`);digestValue(value.argv_sha256,`${label}.argv_sha256`);return value};
const validateProof=(value,session)=>{
 exact(value,['schema_version','status','session_id','sequence','challenge','observer','host','package','service','config','listener','tls','discovery'],'broker proof');if(value.schema_version!==1||value.status!=='verified')throw Error('broker proof identity invalid');uuidValue(value.session_id,'broker proof.session_id');integerValue(value.sequence,'broker proof.sequence',{min:1,max:1000000});digestValue(value.challenge,'broker proof.challenge');if(session&&value.session_id!==session.session_id)throw Error('broker proof session identity invalid');
 const observer=record(value.observer,'broker proof.observer');exact(observer,['bundle_sha256','process'],'broker proof.observer');digestValue(observer.bundle_sha256,'broker proof.observer.bundle_sha256');processValue(observer.process,'broker proof.observer.process');
 const host=record(value.host,'broker proof.host');exact(host,['host_id','machine_identity_sha256','os','os_version','architecture','kernel','native_or_emulated','hypervisor_evidence_sha256'],'broker proof.host');proofTokenValue(host.host_id,'broker proof.host.host_id');digestValue(host.machine_identity_sha256,'broker proof.host.machine_identity_sha256');if(!['macOS','Debian 13'].includes(host.os))throw Error('broker proof.host.os invalid');textValue(host.os_version,'broker proof.host.os_version');if(!['arm64','amd64'].includes(host.architecture))throw Error('broker proof.host.architecture invalid');textValue(host.kernel,'broker proof.host.kernel');if(!['native','emulated'].includes(host.native_or_emulated))throw Error('broker proof.host.native_or_emulated invalid');digestValue(host.hypervisor_evidence_sha256,'broker proof.host.hypervisor_evidence_sha256');
 const pkg=record(value.package,'broker proof.package');exact(pkg,['sha256','manifest_sha256','installed_version','payload_manifest_sha256','installation_receipt_sha256'],'broker proof.package');for(const key of ['sha256','manifest_sha256','payload_manifest_sha256','installation_receipt_sha256'])digestValue(pkg[key],`broker proof.package.${key}`);textValue(pkg.installed_version,'broker proof.package.installed_version');
 const service=record(value.service,'broker proof.service');const common=['mode','target','definition_sha256','state','generation','post_probe_generation','supervisor','hub','process_tree_sha256'];if(service.mode==='installed-deb-systemd'){exact(service,[...common,'invocation_id','control_group','fragment_sha256','drop_in_manifest_sha256','result','exec_main_code','exec_main_status'],'broker proof.service');if(service.target!=='teslatlas-hub.service'||service.state!=='running'||service.control_group!=='/system.slice/teslatlas-hub.service')throw Error('broker proof.service identity invalid');textValue(service.generation,'broker proof.service.generation');textValue(service.post_probe_generation,'broker proof.service.post_probe_generation');digestValue(service.definition_sha256,'broker proof.service.definition_sha256');digestValue(service.process_tree_sha256,'broker proof.service.process_tree_sha256');processValue(service.supervisor,'broker proof.service.supervisor');processValue(service.hub,'broker proof.service.hub');if(!/^[0-9a-f]{32}$/.test(service.invocation_id))throw Error('broker proof.service.invocation_id invalid');for(const key of ['fragment_sha256','drop_in_manifest_sha256'])digestValue(service[key],`broker proof.service.${key}`);textValue(service.result,'broker proof.service.result');textValue(service.exec_main_code,'broker proof.service.exec_main_code',{max:64,pattern:/^[0-9]+$/});integerValue(service.exec_main_status,'broker proof.service.exec_main_status',{max:255})}else if(service.mode==='installed-app-launchagent'){exact(service,[...common,'plist_sha256','wrapper_script_sha256','loaded_state','app_receipt_sha256','app_process'],'broker proof.service');if(!/^gui\/[1-9][0-9]*\/com\.teslatlas\.hub$/.test(service.target)||service.state!=='running'||service.loaded_state!=='loaded')throw Error('broker proof.service identity invalid');textValue(service.generation,'broker proof.service.generation');textValue(service.post_probe_generation,'broker proof.service.post_probe_generation');digestValue(service.definition_sha256,'broker proof.service.definition_sha256');digestValue(service.process_tree_sha256,'broker proof.service.process_tree_sha256');processValue(service.supervisor,'broker proof.service.supervisor');processValue(service.hub,'broker proof.service.hub');for(const key of ['plist_sha256','wrapper_script_sha256','app_receipt_sha256'])digestValue(service[key],`broker proof.service.${key}`);processValue(service.app_process,'broker proof.service.app_process')}else throw Error('broker proof.service.mode invalid');
 const config=record(value.config,'broker proof.config');exact(config,['path','sha256','data_dir','store_id','store_schema_version','scenario_sha256','seed_sha256'],'broker proof.config');pathValue(config.path,'broker proof.config.path',1024);digestValue(config.sha256,'broker proof.config.sha256');pathValue(config.data_dir,'broker proof.config.data_dir',1024);proofTokenValue(config.store_id,'broker proof.config.store_id');integerValue(config.store_schema_version,'broker proof.config.store_schema_version',{min:1,max:2147483647});digestValue(config.scenario_sha256,'broker proof.config.scenario_sha256');digestValue(config.seed_sha256,'broker proof.config.seed_sha256');
 const listener=record(value.listener,'broker proof.listener');exact(listener,['host','port','owner_pid','socket_identity','observed_at_monotonic_ns'],'broker proof.listener');if(listener.host!=='127.0.0.1'||listener.port!==18480)throw Error('broker proof.listener identity invalid');integerValue(listener.owner_pid,'broker proof.listener.owner_pid',{min:1,max:2147483647});textValue(listener.socket_identity,'broker proof.listener.socket_identity');integerValue(listener.observed_at_monotonic_ns,'broker proof.listener.observed_at_monotonic_ns',{min:1});
 const tls=record(value.tls,'broker proof.tls');exact(tls,['endpoint','certificate_der_sha256','verified_chain','verified_hostname','redirect_count'],'broker proof.tls');if(tls.endpoint!=='https://127.0.0.1:18480'||tls.verified_chain!==true||tls.verified_hostname!==true||tls.redirect_count!==0)throw Error('broker proof.tls identity invalid');digestValue(tls.certificate_der_sha256,'broker proof.tls.certificate_der_sha256');
 const discovery=record(value.discovery,'broker proof.discovery');exact(discovery,['hub_id','product_version','response_sha256','profile_id','profile_sha256','validated_response_set_sha256'],'broker proof.discovery');proofTokenValue(discovery.hub_id,'broker proof.discovery.hub_id');textValue(discovery.product_version,'broker proof.discovery.product_version');if(discovery.profile_id!=='hub-http-v1@1.0.0')throw Error('broker proof.discovery.profile_id invalid');for(const key of ['response_sha256','profile_sha256','validated_response_set_sha256'])digestValue(discovery[key],`broker proof.discovery.${key}`);
 return value;
};
const validateDescriptor=(value)=>{exact(value,['status','provenance','endpoint','hub_id','hub_pid','hub_started_at','service_generation','binary_sha256','seed_binary_sha256','profile_id','profile_path','profile_sha256','scenario_path','scenario_sha256','certificate_path'],'broker descriptor');if(value.status!=='ready'||value.provenance!=='installed-package-service'||value.endpoint!=='https://127.0.0.1:18480')throw Error('broker descriptor identity invalid');proofTokenValue(value.hub_id,'broker descriptor.hub_id');integerValue(value.hub_pid,'broker descriptor.hub_pid',{min:1,max:2147483647});textValue(value.hub_started_at,'broker descriptor.hub_started_at');textValue(value.service_generation,'broker descriptor.service_generation');for(const key of ['binary_sha256','seed_binary_sha256','profile_sha256','scenario_sha256'])digestValue(value[key],`broker descriptor.${key}`);if(value.profile_id!=='hub-http-v1@1.0.0')throw Error('broker descriptor.profile_id invalid');for(const key of ['profile_path','scenario_path','certificate_path'])pathValue(value[key],`broker descriptor.${key}`);return value};
const validateInvitation=(value,label)=>{exact(value,['pairingId','secret','expiresAtMs','endpoint','tlsPin','pairingUri'],label);uuidValue(value.pairingId,`${label}.pairingId`);textValue(value.secret,`${label}.secret`,{max:512});integerValue(value.expiresAtMs,`${label}.expiresAtMs`);if(value.endpoint!=='https://127.0.0.1:18480')throw Error(`${label}.endpoint invalid`);digestValue(value.tlsPin,`${label}.tlsPin`);textValue(value.pairingUri,`${label}.pairingUri`,{max:4096});let parsed;try{parsed=new URL(value.pairingUri)}catch{throw Error(`${label}.pairingUri invalid`)}const query=[...parsed.searchParams.entries()];const expected=[['endpoint',value.endpoint],['pairing_id',value.pairingId],['secret',value.secret],['tls_pin',value.tlsPin]];if(parsed.protocol!=='teslatlas-hub:'||parsed.hostname!=='pair'||parsed.port||parsed.username||parsed.password||parsed.pathname||parsed.hash||query.length!==expected.length||query.some((item,index)=>item[0]!==expected[index][0]||item[1]!==expected[index][1]))throw Error(`${label}.pairingUri binding invalid`);return value};
const validateBrokerResult=(operation,result,session)=>{
 record(result,'broker result');
 if(operation.op==='stop'){exact(result,['stopped','events'],'broker stop result');if(result.stopped!==true||!Array.isArray(result.events)||result.events.length>512)throw Error('broker stop result invalid');return result}
 exact(result,['descriptor','proof','invitation','expired_invitation','events'],'broker running result');validateDescriptor(result.descriptor);validateProof(result.proof,session);validateInvitation(result.invitation,'broker result.invitation');validateInvitation(result.expired_invitation,'broker result.expired_invitation');if(result.invitation.tlsPin!==result.proof.tls.certificate_der_sha256||result.expired_invitation.tlsPin!==result.proof.tls.certificate_der_sha256)throw Error('broker invitation TLS binding invalid');if(result.invitation.pairingId===result.expired_invitation.pairingId)throw Error('broker invitation identity invalid');const now=Date.now();if(result.invitation.expiresAtMs<=now||result.expired_invitation.expiresAtMs>=now)throw Error('broker invitation lifetime invalid');if(result.descriptor.hub_id!==result.proof.discovery.hub_id||result.descriptor.service_generation!==result.proof.service.generation||result.descriptor.binary_sha256!==result.proof.service.hub.executable_sha256||result.descriptor.seed_binary_sha256!==result.proof.config.seed_sha256||result.descriptor.profile_sha256!==result.proof.discovery.profile_sha256||result.descriptor.scenario_sha256!==result.proof.config.scenario_sha256)throw Error('broker descriptor binding invalid');if(!Array.isArray(result.events)||result.events.length>512)throw Error('broker running result events invalid');return result;
};
async function privateBytes(filename,maximum,deadline){
 if(deadline!==undefined&&Date.now()>=deadline)throw Error('private read deadline expired');
 if(typeof filename!=='string'||!path.isAbsolute(filename)||await realpath(filename)!==filename)throw Error('private path invalid');
 const handle=await open(filename,'r');try{const before=await handle.stat();if(!before.isFile()||before.uid!==process.getuid()||(before.mode&0o077)||before.size>maximum||before.nlink!==1)throw Error('private file boundary invalid');const raw=await handle.readFile();const after=await handle.stat();if(raw.length>maximum||before.dev!==after.dev||before.ino!==after.ino||before.size!==after.size||before.mtimeMs!==after.mtimeMs)throw Error('private file changed during read');if(deadline!==undefined&&Date.now()>=deadline)throw Error('private read deadline expired');return raw;}finally{await handle.close()}
}
export async function readInstalledLaneConfig(filename,expectedMode){
 const raw=await privateBytes(filename,1048576);let value;try{value=strictJson(raw)}catch{throw Error('installed lane config invalid JSON')}
 exact(value,['schema_version','kind','mode','session_input'],'installed lane config');
 if(value.schema_version!==2||value.kind!=='installed-client-lane'||value.mode!==expectedMode)throw Error('installed lane config identity invalid');
 exact(value.session_input,['path','sha256'],'session input binding');
 const sessionRaw=await privateBytes(value.session_input.path,1048576);if(sha(sessionRaw)!==value.session_input.sha256)throw Error('session input digest mismatch');
 let session;try{session=strictJson(sessionRaw)}catch{throw Error('session input invalid JSON')}
 validateSessionInput(session);
 const adapter=`typescript_${expectedMode}`;if(session.schema_version!==1||session.kind!=='matrix-adapter-session'||session.adapter_id!==adapter||session.client_id!==adapter||!session.cell_id.startsWith(adapter+'__')||session.broker?.kind!=='unix'||session.broker.socket_path!==session.host_session?.broker_socket||session.host_session?.session_id!==session.session_id)throw Error('session input lane binding mismatch');
 return Object.freeze({config:Object.freeze(value),session:Object.freeze(session),sessionRaw,sessionSha256:sha(sessionRaw)});
}

export async function readInstalledAck(filename,{session,sessionSha256,sequence,readyRaw,deadline}){
 const raw=await privateBytes(filename,FRAME_BYTES,deadline);let value;try{value=strictJson(raw)}catch{throw Error('installed acknowledgement invalid JSON')}
 exact(value,['schema_version','type','session_id','cell_id','session_input_sha256','instance_nonce','sequence','ready_sha256','phase','status','action','result'],'installed acknowledgement');
 if(value.schema_version!==1||value.type!=='ack'||value.session_id!==session.session_id||value.cell_id!==session.cell_id||value.session_input_sha256!==sessionSha256||value.instance_nonce!==session.instance_nonce||value.sequence!==sequence||value.ready_sha256!==sha(readyRaw)||value.phase!=='evidence_ready'||value.status!=='accepted'||value.action!=='close_completed')throw Error('installed acknowledgement identity invalid');
 const result=record(value.result,'installed acknowledgement result');exact(result,['path','sha256'],'installed acknowledgement result binding');pathValue(result.path,'installed acknowledgement result.path');digestValue(result.sha256,'installed acknowledgement result.sha256');const resultRaw=await privateBytes(result.path,FRAME_BYTES,deadline);if(sha(resultRaw)!==result.sha256)throw Error('installed acknowledgement result digest mismatch');let close;try{close=strictJson(resultRaw)}catch{throw Error('installed acknowledgement result invalid JSON')};exact(close,['schema_version','session_id','state','journal','final_stopped','cleanup_errors','local_transport'],'installed acknowledgement close result');if(close.schema_version!==1||close.session_id!==session.session_id||close.state!=='closed'||!Array.isArray(close.cleanup_errors)||close.cleanup_errors.length!==0)throw Error('installed acknowledgement close result identity invalid');return value;
}

export class InstalledBroker {
 constructor(session){this.session=session;this.socket=null;this.buffer=Buffer.alloc(0);this.challenge=null;this.sequence=0;this.pending=false;this.failed=false;}
 #poison(error){this.failed=true;this.pending=false;this.socket?.destroy();this.socket=null;return error instanceof Error?error:Error(String(error))}
 async open(deadlineAt){if(this.failed)throw Error('broker is permanently failed');if(this.socket)throw Error('broker already open');try{const deadline=Math.min(Date.now()+10000,deadlineAt??Number.MAX_SAFE_INTEGER);if(deadline<=Date.now())throw Error('broker greeting deadline expired');this.socket=net.createConnection({path:this.session.broker.socket_path});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{cleanup();this.socket.destroy();reject(Error('broker greeting timed out'))},Math.max(1,deadline-Date.now()));const cleanup=()=>{clearTimeout(timer);this.socket.off('connect',connected);this.socket.off('error',failed)};const connected=()=>{cleanup();resolve()};const failed=error=>{cleanup();reject(error)};this.socket.once('connect',connected);this.socket.once('error',failed)});const greeting=await this.#frame(Math.max(1,deadline-Date.now()));exact(greeting,['schema_version','type','session_id','sequence','challenge'],'broker greeting');if(!Number.isInteger(greeting.schema_version)||greeting.schema_version!==1||greeting.type!=='challenge'||greeting.session_id!==this.session.session_id||!Number.isInteger(greeting.sequence)||greeting.sequence!==0||!/^[0-9a-f]{64}$/.test(greeting.challenge))throw Error('broker greeting identity invalid');this.challenge=greeting.challenge;return this;}catch(error){throw this.#poison(error)}}
 async request(operation,deadlineAt){if(this.failed)throw Error('broker is permanently failed');if(this.pending||!this.socket)throw Error('broker request state invalid');try{exact(operation,operation.op==='revoke'?['op','device_id']:['op'],'broker operation');if(!Object.hasOwn(OPERATION_MS,operation.op))throw Error('broker operation invalid');if(operation.op==='revoke')uuidValue(operation.device_id,'broker operation.device_id');const deadline=Math.min(Date.now()+OPERATION_MS[operation.op],deadlineAt??Number.MAX_SAFE_INTEGER);if(deadline<=Date.now())throw Error('broker operation deadline expired');this.pending=true;const requestChallenge=this.challenge;const request={schema_version:1,session_id:this.session.session_id,sequence:++this.sequence,challenge:requestChallenge,...operation};this.socket.write(JSON.stringify(request)+'\n');const reply=await this.#frame(Math.max(1,deadline-Date.now()));const keys=reply.type==='reply'?['schema_version','type','session_id','sequence','challenge','result']:['schema_version','type','session_id','sequence','challenge','error'];exact(reply,keys,'broker reply');if(!Number.isInteger(reply.schema_version)||reply.schema_version!==1||reply.session_id!==this.session.session_id||reply.sequence!==this.sequence||reply.challenge===requestChallenge||!/^[0-9a-f]{64}$/.test(reply.challenge))throw Error('broker reply identity invalid');this.challenge=reply.challenge;if(reply.type!=='reply')throw Error('broker operation failed');const result=validateBrokerResult(operation,reply.result,this.session);if(operation.op!=='stop'){if(result.proof.sequence!==this.sequence)throw Error('broker proof sequence binding invalid');if(result.proof.challenge!==requestChallenge)throw Error('broker proof challenge binding invalid');}return result;}catch(error){throw this.#poison(error)}finally{this.pending=false}}
 close(){this.socket?.end();this.socket=null;}
 async #frame(timeoutMs){const deadline=Date.now()+timeoutMs;while(true){const newline=this.buffer.indexOf(10);if(newline>=0){if(newline>FRAME_BYTES)throw Error('broker frame exceeds bound');const raw=this.buffer.subarray(0,newline);this.buffer=this.buffer.subarray(newline+1);let value;try{value=strictJson(raw)}catch{throw Error('broker frame invalid')};return value}const remaining=deadline-Date.now();if(remaining<=0){this.socket.destroy();throw Error('broker frame timed out')}const chunk=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{cleanup();this.socket.destroy();reject(Error('broker frame timed out'))},remaining);const data=value=>{cleanup();resolve(value)};const end=()=>{cleanup();resolve(null)};const error=value=>{cleanup();reject(value)};const cleanup=()=>{clearTimeout(timer);this.socket.off('data',data);this.socket.off('end',end);this.socket.off('error',error)};this.socket.once('data',data);this.socket.once('end',end);this.socket.once('error',error)});if(chunk===null)throw Error('premature broker EOF');this.buffer=Buffer.concat([this.buffer,chunk]);if(this.buffer.length>FRAME_BYTES+1)throw Error('broker frame exceeds bound')}}
}
